### ISSUE TITLE
Figma Plus seems be broken

### ISSUE THREAD

**Issue by ar-tama** [figma-plus/figma-plus#1]
Hello @cdes ! I’m so exciting I coincidentally find out your cool product. However, today it has been broken on the latest Figma app, according to [the spectrum comment](https://spectrum.chat/figma-plus/requests/is-the-plugin-supported~7330c33d-49cc-488b-96bc-703389e7c3fd). (Now [a download page](https://figmaplus.com/) is 404. Is it because of the incident?)
I want to develop my own extensions using Figma Plus or something.  So...

- Do you have any plan about fix and maintain it?
- What I (and other people) can do help?

**Comment by jackiecorn** [comment]
Sorry for the late response. We have been busy preparing for the public version of Figma Plus.
You can now get Figma Plus from https://figmaplus.com/.
If you are interesting in building plugins, please read our docs at https://docs.figmaplus.com/
Thanks!
