### ISSUE TITLE
Do not work Cmd+C Cmd+V 

### ISSUE THREAD

**Issue by neodisa** [figma-plus/figma-plus#4]
When I am trying to copy anything from one document to another document, I can't do it. And also I cannot insert anything (image, text ..) at all into the document with Cmd+C.  When I remove Figma Plus, all working. 

And thanks for fix " text copied problem" :)

**Comment by jackiecorn** [comment]
What plugins have you installed? Can you try uninstalling all plugins and see if the problem still exists?

**Comment by neodisa** [comment]
Current list of installed plugins:
1. Replace with Components
2. Paste to All
3. Find and Replace
4. Automations
5. Content Generator

Yea, problem solve if uninstall all plugins

My guess is this could be due to one of these plugins:
_Replace with Components
Paste to All_

Because I deleted them and it worked again.

**Comment by jackiecorn** [comment]
Seems like it is a problem caused by the Paste to All plugin, since it's the only one that overrides the Cmd + C shortcut.

I have just tested copying an pasting objects across documents and everything worked fine. If you have the console opened, can you try copying/pasting and show me a screenshot of the console?

**Comment by neodisa** [comment]
I tried again to execute the command (Cmd+C), and still failed. Here is a screenshot of the console
http://prntscr.com/nl1g8h

**Comment by jackiecorn** [comment]
I have fixed the bug in the Paste to All plugin. Can you try it out for me again?

**Comment by neodisa** [comment]
I tried again, but not working. I removed FigmaPlus and added again before trying.
I think is not a big problem for me, when I know which is plugin need disabled

**Comment by jackiecorn** [comment]
I have removed the keyboard shortcut from the Paste to All plugin, the command is now in the right click menu instead of Cmd + V. Please install the plugin again and see if it works. Thanks!

**Comment by neodisa** [comment]
Thanks, everything is working now

**Comment by jackiecorn** [comment]
Awesome!
