### ISSUE TITLE
Blank screen only

### ISSUE THREAD

**Issue by marom99** [figma-plus/figma-plus#7]
Hello, i can't find a some plugins with figma plus,its only blank screen when i'm open figma plus

![image](https://user-images.githubusercontent.com/30464867/57313717-5cb58880-711a-11e9-90e2-3c8a87f1b75c.png)

**Comment by jackiecorn** [comment]
Are you running on the browser or the desktop app?

**Comment by marom99** [comment]
i'm running on google chrome

**Comment by jackiecorn** [comment]
This is likely caused by Adblock, please disable Adblock on all Figma pages and try again.

**Comment by marom99** [comment]
thank you, it has been running normally since I turned off my adblock

![image](https://user-images.githubusercontent.com/30464867/57355018-4bf72800-7197-11e9-9b79-e4685565be3c.png)
